//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.CoursesReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        private int PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoursesReference.CourseServiceSoap")]
    public interface CourseServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetCoursesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourses", ReplyAction="*")]
        School.CoursesReference.GetCoursesResponse GetCourses(School.CoursesReference.GetCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<School.CoursesReference.GetCoursesResponse> GetCoursesAsync(School.CoursesReference.GetCoursesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourses", Namespace="http://tempuri.org/", Order=0)]
        public School.CoursesReference.GetCoursesRequestBody Body;
        
        public GetCoursesRequest() {
        }
        
        public GetCoursesRequest(School.CoursesReference.GetCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCoursesRequestBody {
        
        public GetCoursesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCoursesResponse", Namespace="http://tempuri.org/", Order=0)]
        public School.CoursesReference.GetCoursesResponseBody Body;
        
        public GetCoursesResponse() {
        }
        
        public GetCoursesResponse(School.CoursesReference.GetCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public School.CoursesReference.Course[] GetCoursesResult;
        
        public GetCoursesResponseBody() {
        }
        
        public GetCoursesResponseBody(School.CoursesReference.Course[] GetCoursesResult) {
            this.GetCoursesResult = GetCoursesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CourseServiceSoapChannel : School.CoursesReference.CourseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServiceSoapClient : System.ServiceModel.ClientBase<School.CoursesReference.CourseServiceSoap>, School.CoursesReference.CourseServiceSoap {
        
        public CourseServiceSoapClient() {
        }
        
        public CourseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        School.CoursesReference.GetCoursesResponse School.CoursesReference.CourseServiceSoap.GetCourses(School.CoursesReference.GetCoursesRequest request) {
            return base.Channel.GetCourses(request);
        }
        
        public School.CoursesReference.Course[] GetCourses() {
            School.CoursesReference.GetCoursesRequest inValue = new School.CoursesReference.GetCoursesRequest();
            inValue.Body = new School.CoursesReference.GetCoursesRequestBody();
            School.CoursesReference.GetCoursesResponse retVal = ((School.CoursesReference.CourseServiceSoap)(this)).GetCourses(inValue);
            return retVal.Body.GetCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<School.CoursesReference.GetCoursesResponse> School.CoursesReference.CourseServiceSoap.GetCoursesAsync(School.CoursesReference.GetCoursesRequest request) {
            return base.Channel.GetCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<School.CoursesReference.GetCoursesResponse> GetCoursesAsync() {
            School.CoursesReference.GetCoursesRequest inValue = new School.CoursesReference.GetCoursesRequest();
            inValue.Body = new School.CoursesReference.GetCoursesRequestBody();
            return ((School.CoursesReference.CourseServiceSoap)(this)).GetCoursesAsync(inValue);
        }
    }
}
