//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.StudentsReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentsReference1.StudServiceSoap")]
    public interface StudServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        School.StudentsReference1.GetStudentsResponse GetStudents(School.StudentsReference1.GetStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<School.StudentsReference1.GetStudentsResponse> GetStudentsAsync(School.StudentsReference1.GetStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name lastName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStudents", ReplyAction="*")]
        School.StudentsReference1.InsertStudentsResponse InsertStudents(School.StudentsReference1.InsertStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<School.StudentsReference1.InsertStudentsResponse> InsertStudentsAsync(School.StudentsReference1.InsertStudentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudents", Namespace="http://tempuri.org/", Order=0)]
        public School.StudentsReference1.GetStudentsRequestBody Body;
        
        public GetStudentsRequest() {
        }
        
        public GetStudentsRequest(School.StudentsReference1.GetStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStudentsRequestBody {
        
        public GetStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public School.StudentsReference1.GetStudentsResponseBody Body;
        
        public GetStudentsResponse() {
        }
        
        public GetStudentsResponse(School.StudentsReference1.GetStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public School.StudentsReference1.Student[] GetStudentsResult;
        
        public GetStudentsResponseBody() {
        }
        
        public GetStudentsResponseBody(School.StudentsReference1.Student[] GetStudentsResult) {
            this.GetStudentsResult = GetStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStudents", Namespace="http://tempuri.org/", Order=0)]
        public School.StudentsReference1.InsertStudentsRequestBody Body;
        
        public InsertStudentsRequest() {
        }
        
        public InsertStudentsRequest(School.StudentsReference1.InsertStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStudentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int year;
        
        public InsertStudentsRequestBody() {
        }
        
        public InsertStudentsRequestBody(string lastName, string firstName, int year) {
            this.lastName = lastName;
            this.firstName = firstName;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public School.StudentsReference1.InsertStudentsResponseBody Body;
        
        public InsertStudentsResponse() {
        }
        
        public InsertStudentsResponse(School.StudentsReference1.InsertStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertStudentsResponseBody {
        
        public InsertStudentsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudServiceSoapChannel : School.StudentsReference1.StudServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudServiceSoapClient : System.ServiceModel.ClientBase<School.StudentsReference1.StudServiceSoap>, School.StudentsReference1.StudServiceSoap {
        
        public StudServiceSoapClient() {
        }
        
        public StudServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        School.StudentsReference1.GetStudentsResponse School.StudentsReference1.StudServiceSoap.GetStudents(School.StudentsReference1.GetStudentsRequest request) {
            return base.Channel.GetStudents(request);
        }
        
        public School.StudentsReference1.Student[] GetStudents() {
            School.StudentsReference1.GetStudentsRequest inValue = new School.StudentsReference1.GetStudentsRequest();
            inValue.Body = new School.StudentsReference1.GetStudentsRequestBody();
            School.StudentsReference1.GetStudentsResponse retVal = ((School.StudentsReference1.StudServiceSoap)(this)).GetStudents(inValue);
            return retVal.Body.GetStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<School.StudentsReference1.GetStudentsResponse> School.StudentsReference1.StudServiceSoap.GetStudentsAsync(School.StudentsReference1.GetStudentsRequest request) {
            return base.Channel.GetStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<School.StudentsReference1.GetStudentsResponse> GetStudentsAsync() {
            School.StudentsReference1.GetStudentsRequest inValue = new School.StudentsReference1.GetStudentsRequest();
            inValue.Body = new School.StudentsReference1.GetStudentsRequestBody();
            return ((School.StudentsReference1.StudServiceSoap)(this)).GetStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        School.StudentsReference1.InsertStudentsResponse School.StudentsReference1.StudServiceSoap.InsertStudents(School.StudentsReference1.InsertStudentsRequest request) {
            return base.Channel.InsertStudents(request);
        }
        
        public void InsertStudents(string lastName, string firstName, int year) {
            School.StudentsReference1.InsertStudentsRequest inValue = new School.StudentsReference1.InsertStudentsRequest();
            inValue.Body = new School.StudentsReference1.InsertStudentsRequestBody();
            inValue.Body.lastName = lastName;
            inValue.Body.firstName = firstName;
            inValue.Body.year = year;
            School.StudentsReference1.InsertStudentsResponse retVal = ((School.StudentsReference1.StudServiceSoap)(this)).InsertStudents(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<School.StudentsReference1.InsertStudentsResponse> School.StudentsReference1.StudServiceSoap.InsertStudentsAsync(School.StudentsReference1.InsertStudentsRequest request) {
            return base.Channel.InsertStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<School.StudentsReference1.InsertStudentsResponse> InsertStudentsAsync(string lastName, string firstName, int year) {
            School.StudentsReference1.InsertStudentsRequest inValue = new School.StudentsReference1.InsertStudentsRequest();
            inValue.Body = new School.StudentsReference1.InsertStudentsRequestBody();
            inValue.Body.lastName = lastName;
            inValue.Body.firstName = firstName;
            inValue.Body.year = year;
            return ((School.StudentsReference1.StudServiceSoap)(this)).InsertStudentsAsync(inValue);
        }
    }
}
